### ISSUE TITLE
USER STORY: Add Search field

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#10]
As a **User** I can **Search content** so that **I can find content easily**

**Comment by shahid129** [comment]
**Acceptance Criteria**
- User can search cars
- User can click on the searched cars to view the cars

**Task**

- [x] Add a search option on the page
- [x] Create search.html
- [x] Wire it up with views and url
- [x] The search can look up insensitive case(get records that contain a specified value)
