### ISSUE TITLE
USER STORY: About Page

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#15]
As a **user** I can **view the about page** so that **I know more about the page and find the company's contact details**

**Comment by shahid129** [comment]
**Acceptance Criteria**

- The about page should have our mission, privacy and contact us

**Tasks**

- [x] Create about.html
- [x] Wire it up with views and the url
- [x] Add three sections containing Mission, Your Privacy and Contact us
- [x] Add JQuery for smooth hover effect
