### ISSUE TITLE
USER STORY: Post Ad

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#16]
As a **user** I can **can post my add** so that **I can sell my cars and add details of my car**
#21

**Comment by shahid129** [comment]
**Acceptance Criteria**

- User can post their ads for selling cars
**Tasks**

- [x] Create a model with all necessary fields
- [x] create post_your_add.html
- [x] Wire up the model with views url and forms.py
- [x] Add widgets to forms
- [x] Add styling to the forms
