### ISSUE TITLE
USER STORY: Delete post

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#18]
As a **user** I can **delete my ad** so that **it's no longer visible on the page**
#21

**Comment by shahid129** [comment]
**Acceptance Criteria**
- The user should be able to delete their posts.
- Users should be warned if they really want o delete the post

**Tasks**
- [x] Create a view to delete the post
- [x] Add a modal to the delete button
- [x] Once confirmed to delete, the post should be deleted
