### ISSUE TITLE
USER STORY: Login and Logout

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#2]
As a **User** I can **I can login and logout** so that **I can access my content**
#20

**Comment by shahid129** [comment]
**Acceptance Criteria**

1. User can log in
2. Get a message when log in successful
3. User can Log out
4. Get a message when log out successful

**Task**
- Login
- [x] Create Views and wire it up with urls and login template
- [x] Add views for login successful login message
- [x] Add views to display any errors
- Logout
- [x] Create Views and wire it up with urls and logout template
- [x] Add views for successful logout message
- [x] Add views to display any errors
