### ISSUE TITLE
USER STORY: Email validation on sign up

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#23]
As a **User** I can **receive an email** so that **I can validate my account sign up**

**Comment by shahid129** [comment]
*Acceptance Criteria**

- Users receive an email when they register account
**Tasks**

- [x] Write views 
- [x] Wire up views, url 
- [x] Create utils.py
- [x] Add settings for email in settings.py
