### ISSUE TITLE
USER STORY: Comments

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#3]
As a **User** I can **Comment on a content** so that **I can involve in the conversation*

**Comment by shahid129** [comment]
**Acceptance Criteria**
- Users can comment on any post if they are logged in
- Comments are approved by admin
- Show number of comments

**Task**
- [x]  Create views for comments and link them up with the url
- [x] Restrict not-logged-in users from commenting.
- [x] Add code to show the total number of comments
