### ISSUE TITLE
USER STORY: Register Account

### ISSUE THREAD

**Issue by shahid129** [shahid129/mycar#4]
As a **User** I can **Register an account** so that **I can post my add and comments**
#20

**Comment by shahid129** [comment]
**Tasks**

- [x] Create a registration folder and login.html and register.html
- [x] Wire it up with the views and url
- [x] Redirect to the home page after successful login
- [x] Add widgets and required css class
- [x] Add CSS and bootstrap
